# Generated by Django 5.2 on 2026-02-07 18:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("board_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("workspace", "Workspace"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("background_type", models.CharField(default="color", max_length=20)),
                (
                    "background_value",
                    models.CharField(default="#0079bf", max_length=500),
                ),
                ("position", models.IntegerField(db_index=True, default=0)),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "boards",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("card_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("due_date_complete", models.BooleanField(default=False)),
                (
                    "cover_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("position", models.IntegerField(db_index=True)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="Core.board",
                    ),
                ),
            ],
            options={
                "db_table": "cards",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                ("checklist_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="Core.card",
                    ),
                ),
            ],
            options={
                "db_table": "checklists",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("checked", models.BooleanField(default=False)),
                ("position", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Core.checklist",
                    ),
                ),
            ],
            options={
                "db_table": "checklist_items",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("label_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(max_length=20)),
                ("archived", models.BooleanField(default=False)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="Core.board",
                    ),
                ),
            ],
            options={
                "db_table": "labels",
            },
        ),
        migrations.CreateModel(
            name="CardLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_labels",
                        to="Core.card",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_labels",
                        to="Core.label",
                    ),
                ),
            ],
            options={
                "db_table": "card_labels",
            },
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                ("list_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField(db_index=True)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to="Core.board",
                    ),
                ),
            ],
            options={
                "db_table": "lists",
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="Core.list",
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=100, unique=True),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("bio", models.TextField(blank=True, null=True)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reset_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_when", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="Core.card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_members",
                        to="Core.card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "card_members",
            },
        ),
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("observer", "Observer"),
                        ],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_members",
                        to="Core.board",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "board_members",
            },
        ),
        migrations.CreateModel(
            name="BoardInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="Core.board",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="board",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("attach_id", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=500)),
                ("mime_type", models.CharField(max_length=100)),
                ("size", models.IntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="Core.card",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                ("action_type", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="Core.board",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="Core.card",
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="Core.list",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(fields=["card"], name="checklists_card_id_79370d_idx"),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(
                fields=["checklist"], name="checklist_i_checkli_c5af2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(
                fields=["position"], name="checklist_i_positio_17c635_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(fields=["board"], name="labels_board_i_789a0b_idx"),
        ),
        migrations.AddIndex(
            model_name="cardlabel",
            index=models.Index(fields=["card"], name="card_labels_card_id_e85f39_idx"),
        ),
        migrations.AddIndex(
            model_name="cardlabel",
            index=models.Index(fields=["label"], name="card_labels_label_i_849880_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="cardlabel",
            unique_together={("card", "label")},
        ),
        migrations.AddIndex(
            model_name="list",
            index=models.Index(fields=["board"], name="lists_board_i_db57e8_idx"),
        ),
        migrations.AddIndex(
            model_name="list",
            index=models.Index(fields=["position"], name="lists_positio_84e2dd_idx"),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["list"], name="cards_list_id_08110b_idx"),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["board"], name="cards_board_i_8aa48e_idx"),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["position"], name="cards_positio_ed7a8d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["card"], name="comments_card_id_82252d_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["user"], name="comments_user_id_8613ff_idx"),
        ),
        migrations.AddIndex(
            model_name="cardmember",
            index=models.Index(fields=["card"], name="card_member_card_id_36280f_idx"),
        ),
        migrations.AddIndex(
            model_name="cardmember",
            index=models.Index(fields=["user"], name="card_member_user_id_f885e0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="cardmember",
            unique_together={("card", "user")},
        ),
        migrations.AddIndex(
            model_name="boardmember",
            index=models.Index(fields=["board"], name="board_membe_board_i_4a22c9_idx"),
        ),
        migrations.AddIndex(
            model_name="boardmember",
            index=models.Index(fields=["user"], name="board_membe_user_id_aa11b9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="boardmember",
            unique_together={("board", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="boardinvitation",
            unique_together={("board", "email")},
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(fields=["creator"], name="boards_creator_470de2_idx"),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(fields=["position"], name="boards_positio_804418_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["card"], name="attachments_card_id_0adf9b_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["uploaded_by"], name="attachments_uploade_77499a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["board"], name="activities_board_i_20443b_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["card"], name="activities_card_id_c702c4_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["list"], name="activities_list_id_da6342_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["user"], name="activities_user_id_2fedd2_idx"),
        ),
    ]
