# Generated by Django 5.2 on 2026-05-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password_hash",
        ),
    ]
