# Generated by Django 5.2 on 2026-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_remove_password_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardinvitation",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("observer", "Observer")],
                default="member",
                max_length=10,
            ),
        ),
    ]
