# Generated by Django 5.2 on 2025-04-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_remove_category_user_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Description', max_length=255),
        ),
    ]
