# Generated by Django 5.2 on 2025-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Élevée')], default=2),
        ),
    ]
