# Generated by Django 5.2 on 2025-04-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteduserontask',
            name='email_invited_user',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='inviteduserontask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
