# Generated by Django 5.2 on 2025-04-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_inviteduserontask_email_invited_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inviteduserontask',
            old_name='task',
            new_name='id_task',
        ),
    ]
